#!/usr/bin/env bash
# Installs Nginx and configures it to return 'Hello World!' on the root URL

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
