#!/usr/bin/env bash
# A Bash script to install Nginx, listens for port 80, returns a webpage when querying nginx at root
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
