#!/usr/bin/env bash
# This script configures Nginx in 7 lines
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx restart